import AdicionarProduto from '../components/AdicionarProduto'
import FirstBloco from '../components/FirstBloco'
import Footer from '../components/Footer'
import Header from '../components/header'
import ListaProdutos from '../components/ListaProdutos'
import styles from '../styles/Home.module.css'
import Head from 'next/head'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>I want it, I got it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <FirstBloco />
      <AdicionarProduto />
      <ListaProdutos />
      <Footer />
    </div>
  )
}
